### ISSUE TITLE
Add 'read' property on sent notifications

### ISSUE THREAD

**Issue by mvantellingen** [scdoshi/django-notifier#1]
Heya,

I want to display the sent notifications also in the user's dashboard (or menu) with an unread count. 

It would be great if this could be done as property of the SentNotification model. This way we can (in the future) also include an image in the html emails which automatically sets the 'read' boolean.

**Comment by scdoshi** [comment]
I like the idea. I'll think about how to implement it.

**Comment by scdoshi** [comment]
'read' field added on SentNotification model in version 0.7. I also wanted to add urls that would automatically set the read property, so that webhooks could be set, but maybe in a later version.
