### ISSUE TITLE
Use model_utils instead of django-bits

### ISSUE THREAD

**Issue by mvantellingen** [scdoshi/django-notifier#2]
Hey,

Second issue (because this app looks really promising). Will you accept a patch to use model_utils TimestampedModel instead of the variant in django-bits. Reason for this is that model_utils is more 'standard' and django-bits seems like a collection of random utils :-)

**Comment by scdoshi** [comment]
I have been thinking of maybe removing the dependency anyways.

**Comment by scdoshi** [comment]
Fixed in latest master.
